allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Force Kotlin serialization plugin version to avoid conflict with background_downloader
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-serialization:2.1.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
    }
}

configurations.all {
    resolutionStrategy {
        force "org.jetbrains.kotlin:kotlin-serialization:2.1.0"
        force "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
        force "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin:2.1.0"
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    
    // Fix background_downloader Kotlin serialization plugin version conflict
    if (project.name == 'background_downloader') {
        project.buildscript {
            dependencies {
                classpath "org.jetbrains.kotlin:kotlin-serialization:2.1.0"
                classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}