name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    environment: production
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Install Flutter Dependencies
      run: flutter pub get

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod --version

    - name: Build iOS (IPA, unsigned)
      run: |
        flutter clean
        flutter pub get
        echo "Using build number $BUILD_NUMBER"
        flutter build ipa --release --no-codesign --build-number $BUILD_NUMBER

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        if-no-files-found: warn
        path: |
          build/ios/ipa/
          build/ios/archive/Runner.xcarchive